// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dg052crp5dtzbXcHsPQBxXdnwiSYTFM',
    appId: '1:33306351265:web:8541e4a7f46ae7fb8442e0',
    messagingSenderId: '33306351265',
    projectId: 'bankpick-f9337',
    authDomain: 'bankpick-f9337.firebaseapp.com',
    storageBucket: 'bankpick-f9337.appspot.com',
    measurementId: 'G-K6H1WJCPRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCocfUdPFaZfJJBW6VNCMQHu8yoGMRd5Qs',
    appId: '1:33306351265:android:d709efecc4a876a38442e0',
    messagingSenderId: '33306351265',
    projectId: 'bankpick-f9337',
    storageBucket: 'bankpick-f9337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp-SjacnjyvPV6Xbuk0G2YIzEmhIiRDE',
    appId: '1:33306351265:ios:e26249e8bde8e4d68442e0',
    messagingSenderId: '33306351265',
    projectId: 'bankpick-f9337',
    storageBucket: 'bankpick-f9337.appspot.com',
    iosBundleId: 'io.github.liuy97.bankpick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyp-SjacnjyvPV6Xbuk0G2YIzEmhIiRDE',
    appId: '1:33306351265:ios:e26249e8bde8e4d68442e0',
    messagingSenderId: '33306351265',
    projectId: 'bankpick-f9337',
    storageBucket: 'bankpick-f9337.appspot.com',
    iosBundleId: 'io.github.liuy97.bankpick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_dg052crp5dtzbXcHsPQBxXdnwiSYTFM',
    appId: '1:33306351265:web:a45e495dc643f2618442e0',
    messagingSenderId: '33306351265',
    projectId: 'bankpick-f9337',
    authDomain: 'bankpick-f9337.firebaseapp.com',
    storageBucket: 'bankpick-f9337.appspot.com',
    measurementId: 'G-E7KJB4XHFV',
  );
}